LoginCentral/Controllers/SessionController.cs
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using LoginCentral.Entities;
using LoginCentral.HttpModule;

namespace LoginCentral.Controllers
{
    public class SessionController : Controller
    {
        // GET: Session

        [AllowAnonymous]
        public ActionResult Index()
        {
            var roles = new List<Role>();

            if (Request.IsAuthenticated)
            {
                using (var ctx = new LoginCentralContext())
                {
                    var dbRoles = ctx.Roles.ToList();

                    roles.AddRange(dbRoles);
                }
            }
            return View(roles);
        }

        [HttpGet, AllowAnonymous]
        public ActionResult New()
        {
            if (Request.IsAuthenticated)
            {
                return Redirect(FormsAuthentication.GetRedirectUrl(User.Identity.Name, true));
            }
            return View();
        }

        [HttpPost, AllowAnonymous, ValidateAntiForgeryToken]
        public ActionResult New(string userName, string password, bool rememberMe = true)
        {
            FormsAuthentication.SignOut();

            using (var ctx = new LoginCentralContext())
            {
                var dbUser = ctx.Users.FirstOrDefault(x => x.Login.Equals(userName));

                if (dbUser == null || !dbUser.Status)
                {
                    ModelState.AddModelError("", "Usuário inexistente");
                }
                else if (SaltedHash.Instance.VerifyHashString(password, dbUser.Hash, dbUser.Salt))
                {
                    Response.SetAuthCookie(dbUser.Login, rememberMe, dbUser.UserRoles);

                    //FormsAuthentication.SetAuthCookie(dbUser.Login, true);
                    var url = HttpUtility.UrlDecode(FormsAuthentication.GetRedirectUrl(dbUser.Login, true));
                    if (string.IsNullOrEmpty(url))
                    {
                        return RedirectToAction("Index");
                    }
                    return Redirect(url);
                }

                ModelState.AddModelError("", "Senha inválida");
                return View();
            }
        }

        //[Authorize]
        public ActionResult AddRole(int? roleId)
        {
            if (!roleId.HasValue)
            {
                return RedirectToAction("Index");
            }

            using (var ctx = new LoginCentralContext())
            {
                var role = ctx.Roles.FirstOrDefault(x => x.Id == roleId.Value);
                if (role == null || !role.Status)
                {
                    return RedirectToAction("Index");
                }

                var user = ctx.Users
                    .Include(x => x.UserRoles)
                    .Include(x => x.UserRoles.Select(s => s.Role))
                    .FirstOrDefault(x => x.Login.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase));

                if (user == null)
                {
                    return RedirectToAction("Index");
                }

                CacheApi.ClearUserFromCache(User);

                if (user.UserRoles.Any(x => x.RoleId == roleId.Value))
                {
                    //já possui a role
                    return RedirectToAction("Index");
                }

                var userrole = new UserRole()
                {
                    User = user,
                    Role = role
                };

                ctx.UserRoles.Add(userrole);
                try
                {
                    ctx.SaveChanges();
                }
                finally
                {

                }

            }

            return RedirectToAction("Index");
        }

        //[Authorize]
        public ActionResult RemoveRole(int? roleId)
        {
            if (!roleId.HasValue)
            {
                return RedirectToAction("Index");
            }

            using (var ctx = new LoginCentralContext())
            {
                var role = ctx.Roles.FirstOrDefault(x => x.Id == roleId.Value);
                if (role == null || !role.Status)
                {
                    return RedirectToAction("Index");
                }

                var user = ctx.Users
                    .Include(x => x.UserRoles)
                    .Include(x => x.UserRoles.Select(s => s.Role))
                    .FirstOrDefault(x => x.Login.Equals(User.Identity.Name, StringComparison.OrdinalIgnoreCase));

                if (user == null)
                {
                    return RedirectToAction("Index");
                }

                var existe = user.UserRoles.FirstOrDefault(x => x.RoleId == roleId.Value);
                if (existe != null)
                {
                    ctx.UserRoles.Remove(existe);
                    try
                    {
                        ctx.SaveChanges();
                    }
                    finally
                    {
                        CacheApi.ClearUserFromCache(User);
                    }
                }
            }

            return RedirectToAction("Index");
        }

        [AllowAnonymous]
        public ActionResult Delete()
        {
            if (Request.IsAuthenticated)
            {
                FormsAuthentication.SignOut();
                Session.Abandon();
            }
            return RedirectToAction("Index");
        }

        [CustomAuthorize(Roles = "Aluno")]
        public ActionResult Aluno()
        {
            return Content("Sou um aluno!");
        }

        [CustomAuthorize(Roles = "Funcionario")]
        public ActionResult Funcionario()
        {
            return Content("Sou um funcionário!");
        }

        [CustomAuthorize(Roles = "Admin")]
        public ActionResult Admin()
        {
            return Content("Sou um Admin");
        }
    }
}

LoginCentral/Views/Session/Index.cshtml
@model List<LoginCentral.Entities.Role>
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
@if (Request.IsAuthenticated)
{
    <h3>Bem vindo, @Context.User.Identity.Name</h3>
    <div class="well">
        <p>Você participa dos seguintes grupos:</p>
        <ul>
            @foreach (var role in Model)
            {
                if (User.IsInRole(role.RoleName))
                {
                    <li>@role.RoleName [@Html.ActionLink("Remover", "RemoveRole", new {roleId = role.Id})] [@Html.ActionLink("Testar", role.RoleName)]</li>
                }
                else
                {
                    <li>@role.RoleName [@Html.ActionLink("Adicionar", "AddRole", new {roleId = role.Id})] [@Html.ActionLink("Testar", role.RoleName)]</li>
                }
            }
        </ul>
        
        @Html.ActionLink("Sair", "Delete")
    </div>
}
else
{
    <h3>Você não está autenticado. Faça o login.</h3>
    @Html.ActionLink("Entrar", "New")
}
<div class="well">
    @if (Request.IsLocal)
    {
        <p><a href="http://localhost:10945/">EAD</a></p>
        <p><a href="http://localhost:11995/">Portal</a></p>
    }
    else
    {
        <p><a href="http://ead.apphb.com/">EAD</a></p>
        <p><a href="http://portal-3.apphb.com/">Portal</a></p>
    }
</div>

LoginCentral/Views/Session/New.cshtml
@{
    ViewBag.Title = "New";
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Signin Template for Bootstrap</title>

    <!-- Bootstrap core CSS -->
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />

    <!-- Custom styles for this template -->
    <style type="text/css">
        body {
            padding-top: 40px;
            padding-bottom: 40px;
            background-color: #eee;
        }

        .form-signin {
            max-width: 330px;
            padding: 15px;
            margin: 0 auto;
        }

            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }

            .form-signin .checkbox {
                font-weight: normal;
            }

            .form-signin .form-control {
                position: relative;
                height: auto;
                -webkit-box-sizing: border-box;
                -moz-box-sizing: border-box;
                box-sizing: border-box;
                padding: 10px;
                font-size: 16px;
            }

                .form-signin .form-control:focus {
                    z-index: 2;
                }

            .form-signin input[type="email"] {
                margin-bottom: -1px;
                border-bottom-right-radius: 0;
                border-bottom-left-radius: 0;
            }

            .form-signin input[type="password"] {
                margin-bottom: 10px;
                border-top-left-radius: 0;
                border-top-right-radius: 0;
            }
    </style>
</head>

<body>

    <div class="container">

        <form method="POST" class="form-signin" role="form">
            
            @Html.AntiForgeryToken()

            @Html.ValidationSummary()

            <h2 class="form-signin-heading">Please sign in</h2>
            <input id="UserName" name="UserName" type="text" class="form-control" placeholder="Usuário" required autofocus>
            <input id="Password" name="Password" type="password" class="form-control" placeholder="Senha" required>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>

    </div> <!-- /container -->


    <div class="well">
        @if (Request.IsLocal)
        {
            <p><a href="http://localhost:10945/">EAD</a></p>
            <p><a href="http://localhost:11995/">Portal</a></p>
        }
        else
        {
            <p><a href="http://ead.apphb.com/">EAD</a></p>
            <p><a href="http://portal-3.apphb.com/">Portal</a></p>
        }

        @Html.ActionLink("Sair", "Delete")
    </div>
</body>
</html>

LoginCentral/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script src="arquivo-inexistente.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Login Central", "Index", "Session", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav"></ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>